### ISSUE TITLE
Can you give us a direct links for models?Baidu links or google drive?

### ISSUE THREAD

**Issue by DeepTiming** [CCC-123/Hydraplus_Net#8]

**Comment by zacario-li** [comment]
> _No description provided._

https://pan.baidu.com/s/1jEQpMzjZHbH_QAXMZlHkpQ 提取码: 9ty6
This is HP net model, use this cmd to test 
`python test.py -m HP -p checkpointpath `

**Comment by DeepTiming** [comment]
Thank you!
